# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf7da8143e512f568e89b271cee7179fcbe740dc4e7f3982d712b806e3896de7d5be72544a0aaddbaa38efa403fe99ba989a2ef8bc12fcb42d05af01338892ce

test:
  secret_key_base: 0d399eb6c288d19c82c9cdfc370e7aca7dd8a4431bdd43072274f60ed3a8b3a4324d3bde93610c134e3e14ffd9e962c93ccddd6361f255e5211fd460c869f14b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
